name: Main Workflow

on: 
  push:
    branches:
      - nodejs_jest_job

jobs:
  build:
    name: linter_execution
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
          
  segundojob:
    name: test-execution
    runs-on: ubuntu-latest
    
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm install
      - run: npm test

      uses: actions/setup-node@v2
      with:
        node-version: '12'
      - run: npm install
      - run: npm test
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run jest tests
        run:
          npm install jest
          npm test




          

