name: Main Workflow

on: [push]

jobs:
  primerjob:
  build:
    name: linter_execution
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linter execution
        uses: docker://github/super-linter:v3.0.1
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

  segundojob:
    name: test-execution
    runs-on: ubuntu-lastest

    steps:
      - name: Chechout code
        uses: actions/checkout@v2

      - name: Run jest tests
        run:
          npm install jest
          npm test

          